name: HH Apply Jobs

on:
  schedule:
    - cron: "0 6,9,12 * * *"   # 09:00, 12:00, 15:00 MSK (UTC+3) = 06:00, 09:00, 12:00 UTC
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run apply jobs
        env:
          HH_CLIENT_ID: ${{ secrets.HH_CLIENT_ID }}
          HH_CLIENT_SECRET: ${{ secrets.HH_CLIENT_SECRET }}
          HH_REFRESH_TOKEN: ${{ secrets.HH_REFRESH_TOKEN }}
          HH_ACCESS_TOKEN: ${{ secrets.HH_ACCESS_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python -m hh_bump.apply
